version: '3.8'

services:
  database:
    image: mysql:latest
    container_name: pizzaria_db
    environment:
      MYSQL_DATABASE: pizzaria_database
      MYSQL_USER: pizzaria_user
      MYSQL_PASSWORD: pizzaria_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
